import {ReactComponent as leaf} from './leaf.svg';
import {ReactComponent as leafGray} from './leaf_gray.svg';
import {ReactComponent as question} from './question.svg';
import {ReactComponent as my} from './my.svg';
import {ReactComponent as close} from './close.svg';
import {ReactComponent as logo} from './logo.svg';
import {ReactComponent as treeButton} from './treeButton.svg';
import {ReactComponent as arrow} from './arrow.svg';
import {ReactComponent as coin} from './coin.svg';
import {ReactComponent as participant} from './participant.svg';
import {ReactComponent as testTree} from './testTree.svg';
import {ReactComponent as success} from './success.svg';
export {leaf};
export {leafGray};
export {question};
export {my};
export {close};
export {logo};
export {treeButton};
export {arrow};
export {coin};
export {participant};
export {testTree};
export {success};
