import {ReactComponent as arrow} from './arrow.svg';
import {ReactComponent as camera} from './camera.svg';
import {ReactComponent as check} from './check.svg';
import {ReactComponent as close} from './close.svg';
import {ReactComponent as dropDown} from './dropDown.svg';
import {ReactComponent as goBack} from './goBack.svg';
import {ReactComponent as goMore} from './goMore.svg';
import {ReactComponent as earth} from './earth.svg';
import {ReactComponent as intro_1} from './intro_1.svg';
import {ReactComponent as intro_2} from './intro_2.svg';
import {ReactComponent as intro_3} from './intro_3.svg';
import {ReactComponent as intro_4} from './intro_4.svg';
import {ReactComponent as leafGray} from './leaf_gray.svg';
import {ReactComponent as leaf} from './leaf.svg';
import {ReactComponent as logo} from './logo.svg';
import {ReactComponent as my} from './my.svg';
import {ReactComponent as noticeOff} from './noticeOff.svg';
import {ReactComponent as noticeOn} from './noticeOn.svg';
import {ReactComponent as onBoard_1} from './onBoard_1.svg';
import {ReactComponent as onBoard_2} from './onBoard_2.svg';
import {ReactComponent as onBoard_3} from './onBoard_3.svg';

import {ReactComponent as participant} from './participant.svg';
import {ReactComponent as question} from './question.svg';
import {ReactComponent as setting} from './setting.svg';
import {ReactComponent as share} from './share.svg';
import {ReactComponent as success} from './success.svg';
import {ReactComponent as testTree} from './testTree.svg';
import {ReactComponent as token} from './token.svg';
import {ReactComponent as treeBao_1} from './treeBao_1.svg';
import {ReactComponent as treeBao_2} from './treeBao_2.svg';
import {ReactComponent as treeBao_3} from './treeBao_3.svg';
import {ReactComponent as treeButton} from './treeButton.svg';
import {ReactComponent as treeH_1} from './treeH_1.svg';
import {ReactComponent as treeH_2} from './treeH_2.svg';
import {ReactComponent as treeH_3} from './treeH_3.svg';
import {ReactComponent as treeJp_1} from './treeJp_1.svg';
import {ReactComponent as treeJp_2} from './treeJp_2.svg';
import {ReactComponent as treeJp_3} from './treeJp_3.svg';
import {ReactComponent as treeMj_1} from './treeMj_1.svg';
import {ReactComponent as treeMj_2} from './treeMj_2.svg';
import {ReactComponent as treeMj_3} from './treeMj_3.svg';
import {ReactComponent as treeOrange_1} from './treeOrange_1.svg';
import {ReactComponent as treeOrange_2} from './treeOrange_2.svg';
import {ReactComponent as treeOrange_3} from './treeOrange_3.svg';
import {ReactComponent as treeSo_1} from './treeSo_1.svg';
import {ReactComponent as treeSo_2} from './treeSo_2.svg';
import {ReactComponent as treeSo_3} from './treeSo_3.svg';
import {ReactComponent as treeYj_1} from './treeYj_1.svg';
import {ReactComponent as treeYj_2} from './treeYj_2.svg';
import {ReactComponent as treeYj_3} from './treeYj_3.svg';

export {arrow};
export {camera};
export {check};
export {close};
export {dropDown};
export {goBack};
export {goMore};
export {earth};
export {intro_1};
export {intro_2};
export {intro_3};
export {intro_4};
export {leafGray};
export {leaf};
export {logo};
export {my};
export {noticeOff};
export {noticeOn};
export {onBoard_1};
export {onBoard_2};
export {onBoard_3};
export {participant};
export {question};
export {setting};
export {share};
export {success};
export {testTree};
export {token};
export {treeBao_1};
export {treeBao_2};
export {treeBao_3};
export {treeButton};
export {treeH_1};
export {treeH_2};
export {treeH_3};

export {treeJp_1};
export {treeJp_2};
export {treeJp_3};
export {treeMj_1};
export {treeMj_2};
export {treeMj_3};
export {treeOrange_1};
export {treeOrange_2};
export {treeOrange_3};
export {treeSo_1};
export {treeSo_2};
export {treeSo_3};
export {treeYj_1};
export {treeYj_2};
export {treeYj_3};
